version: "3.5"
services:
  transactions:
    hostname: transactions
    image: transactions:latest
    build:
      context: .
    restart: always
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - mongodb
      - rabbitmq
  mongodb:
    image: bitnami/mongodb:5.0
    ports:
      - "27017:27017"
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      ALLOW_EMPTY_PASSWORD: 'yes'
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
